all:
  children:
    hub:
      hosts:
        server01:
          ansible_host: 10.233.220.147
                    
    peers:
      hosts:
        node01:
          ansible_host: 10.233.220.179
        node02:
          ansible_host: 10.233.220.74
        node03:
          ansible_host: 10.233.220.56
