- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Add pip lib from Ubuntu repo for docker
  apt:
    name: 
      - python3-docker
      - python3-requests
    state: latest