ansible_user: ubuntu
ansible_ssh_private_key_file: /root/.ssh/id_rsa_ansible.pem
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

wireguard_network: fd86:abcd::/64
wireguard_port: 51820
wireguard_interface: wg0
wireguard_path: "/etc/wireguard"
private_key_path: "/etc/wireguard/{{ wireguard_interface }}_privatekey"
public_key_path: "/etc/wireguard/{{ wireguard_interface }}_publickey"